# -*- coding: utf-8 -*-
"""A1_1_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlzYxE1Etd2vn4IAPrm-xyM8hUhlBKUb

### Load libraries
"""

import re
import unittest
from typing import List

"""#### Question 1: Validate an Email Address"""

import re
def is_valid_email(email: str) -> bool:
# Matches standard email formats like user@example.com

    pattern = r'^[\w\.-]+@[\w\.-]+\.\w{2,}$'

    return bool(re.match(pattern, email))

# Example Usage (Testing the function)
print(f"chipo.jaya@email.gwu.edu: {is_valid_email('chipo.jaya@email.gwu.edu')}")
print(f"chipo.jaya@gwmail.gwu.edu: {is_valid_email('chipo.jaya@gwmail.gwu.edu')}")
print(f"chipo.jaya@gwu.edu: {is_valid_email('chipo.jaya@gwu.edu')}")
print(f"chipo.jaya@gedu: {is_valid_email('chipo.jaya@gedu')}")

"""#### Question 2: Extract All Phone Numbers from a Text"""

def extract_phone_numbers(text):
    # Matches phone numbers in format 123-456-7890
    pattern = r'\b\d{3}-\d{3}-\d{4}\b'

    # re.findall returns a list of all non-overlapping matches of the pattern.
    return re.findall(pattern, text)

# Example Usage (Testing the function)
sample_text = "Contact us at 123-456-7890 or 987-654-3210."

found_numbers = extract_phone_numbers(sample_text)

print(f"Input Text: \"{sample_text}\"")
print(f"Extracted Phone Numbers: {found_numbers}")

"""#### Question 3: Replace All Digits with a Hash Symbol"""

def replace_digits(text: str) -> str:
    # Replaces all digits (0–9) with #
    pattern = r'\d'
    return re.sub(pattern, '#', text)

# Example Usage (Testing the function)
sample_text = "I have 30 apples and 5000 oranges."
result = replace_digits(sample_text)

print(f"Original Text: {sample_text}")
print(f"Resulting Text: {result}")

"""#### Question 4: Find All Words Starting with a Capital Letter"""

def find_capital_words(text):
    # Matches words beginning with an uppercase letter
    pattern = r'\b[A-Z][a-zA-Z]*\b'

    return re.findall(pattern, text)

# Example
sample_text = " I am A text analytics coder."

found_words = find_capital_words(sample_text)

print(f"Original Text: {sample_text}")
print(f"Extracted Capital Words: {found_words}")

"""#### Question 5: Check if a String is a Valid Date (DD-MM-YYYY)"""

def is_valid_date(date_str: str) -> bool:
    # Matches valid dates where day 01–31, month 01–12, year 4 digits
    pattern = r'^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-\d{4}$'
    return bool(re.match(pattern, date_str))

    # re.match checks for a match only at the beginning of the string.
    # We use bool() to return True/False based on whether a match object is found.
    return bool(re.match(pattern, date_str))

# Example Usage (Testing the function)
valid_date = "20-02-1994"
invalid_day = "32-02-1994"
invalid_month = "10-13-1994"
invalid_format = "1-1-194"

print(f"'{valid_date}' is valid: {is_valid_date(valid_date)}")
print(f"'{invalid_day}' is valid: {is_valid_date(invalid_day)}")
print(f"'{invalid_month}' is valid: {is_valid_date(invalid_month)}")
print(f"'{invalid_format}' is valid: {is_valid_date(invalid_format)}")

"""#### Bonus: Improve Question 5 to reject invalid dates like '31-02-2025' or '30-02-2025.'"""

def is_valid_february_date(date_str: str) -> bool:
  # Matches valid dates where day 01–31, month 01–12, year 4 digits
  pattern = r'^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-\d{4}$'
  return bool(re.match(pattern, date_str))

  pattern = r'^(0[1-9]|1\d|2[0-8])-02-\d{4}$'

  # re.match checks for a match only at the beginning of the string.
  # The start (^) and end ($) anchors ensure the whole string must match.
  return bool(re.match(pattern, date_str))

  # Example Usage (Testing the function)
  valid_feb = "28-02-1994"       # Valid February (non-leap year)
  valid_early_feb = "05-02-1994" # Valid early February
  invalid_29_in_feb = "29-02-1994" # Invalid: 29 days (rejects all leap years)
  invalid_30_in_feb = "30-02-1994" # Invalid: 30 days in February
  invalid_31_in_feb = "31-02-1994" # Invalid: 31 days in February

  print(f"'{valid_feb}' is valid: {is_valid_february_date(valid_feb)}")
  print(f"'{valid_early_feb}' is valid: {is_valid_february_date(valid_early_feb)}")
  print(f"'{invalid_29_in_feb}' is valid: {is_valid_february_date(invalid_29_in_feb)}")
  print(f"'{invalid_30_in_feb}' is valid: {is_valid_february_date(invalid_30_in_feb)}")
  print(f"'{invalid_31_in_feb}' is valid: {is_valid_february_date(invalid_31_in_feb)}")







